# Generated by Django 3.2.6 on 2021-08-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='color',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='کد رنگ'),
        ),
    ]
