# Generated by Django 3.2.6 on 2021-08-21 15:33

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_service_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='beautyshop',
            name='services',
            field=models.JSONField(default=main.models.default_json_field(), verbose_name='خدمات'),
        ),
        migrations.AddField(
            model_name='beautyshop',
            name='user_rate',
            field=models.JSONField(default=main.models.default_json_field(), verbose_name='امتیاز کاربران'),
        ),
        migrations.AddField(
            model_name='order',
            name='services',
            field=models.JSONField(default=main.models.default_json_field(), verbose_name='خدمات خریداری شده'),
        ),
        migrations.AlterField(
            model_name='beautyshop',
            name='post_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد پست'),
        ),
    ]
